apiVersion: v1
kind: LimitRange
metadata:
  name: resource-constraints-lr
  namespace: resource-constraints-demo
spec:
  limits:
  - max:
      memory: 128Mi
      cpu: 0.3
    min:
      memory: 32Mi
      cpu: 0.1
    type: Container