apiVersion: v1
kind: Pod
metadata:
  name: resource-constraints-pod
spec:
  containers:
  - name: resource-constraints-ctr
    image: httpd:2.4
    resources:
      limits:
        memory: "96Mi"
        cpu: 0.3
      requests:
        memory: "64Mi"
        cpu: 0.2