image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
replicas: 3
ports:
  containerPort: 80
service:
  type: ""
  port: 8080
resources:
  limits:
    memory: "128Mi"
    cpu: "500m"
topologySpreadConstraints:
  enabled: false