apiVersion: v1
kind: Pod
metadata:
 name: pod-sa
spec:
 serviceAccountName: training-sa
 namespace: wsc-kubernetes-training-sa
 - name: alpine
   image: alpine:3.9
   command:
    - "sleep"
    - "10000"