kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: admin-binding
subjects:
 - kind: User
   name: akram.blouza@wescale.fr
roleRef:
 kind: ClusterRole
 name: admin-role
 apiGroup: rbac.authorization.k8s.io