---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prom-pub
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
    nodePort: 32601
  selector:
    app: prometheus
    prometheus: k8s
---
apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: alertmanager-pub
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
    nodePort: 32602
  selector:
    alertmanager: main
    app: alertmanager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: grafana-pub
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
    nodePort: 32603
  selector:
    app: grafana