---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example
  labels:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-pv
  namespace: nginx-example
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      pv: nginx
  template:
    metadata:
      labels:
        app: nginx
        pv: nginx
    spec:
      initContainers:
      - name: init
        image: busybox
        command: ['sh']
        args:
          - -c
          - |
            if ! grep -q "Hello World" "/usr/share/nginx/html/index.html"; then
              echo "<h1>Hello world $HOSTNAME</h1>" > /usr/share/nginx/html/index.html
            fi
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-pv-storage
      containers:
      - image: nginx:1.17.6
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-pv-storage
      volumes:
        - name: nginx-pv-storage
          persistentVolumeClaim:
            claimName: nginx-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pv-claim
  namespace: nginx-example
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    pv: nginx
  name: my-nginx-pv
  namespace: nginx-example
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
    pv: nginx
  type: NodePort