apiVersion: v1
kind: LimitRange
metadata:
  name: default-requests-and-limits
  namespace: default-resources-config
spec:
  limits:
  - default:
      memory: 64Mi
      cpu: 0.2
    defaultRequest:
      memory: 32Mi
      cpu: 0.1
    type: Container