apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mysql-prom-pod
  labels:
    prometheus: k8s
    role: alert-rules
  namespace: monitoring
spec:
  groups:
    - name: wordpress.mysql
      rules:
        - alert: NoRunningMysql
          annotations:
            description: Targets are down.
            summary: Targets are down
          expr: up{app="wordpress",tier="mysql"} < 1
          for: 10m
          labels:
            severity: warning
  