apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-tcp-udp
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
  egress:
  - {}
  ingress:
  - {}