apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: my-db
spec:
  replicas: 1
  secretName: root-secret
  mysqlConf:
    max_allowed_packet: "128M"
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi