apiVersion: v1
kind: Pod
metadata:
  name: nginx-00
  namespace: scheduling
  labels:
    app: app0
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: worker-0
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-01
  namespace: scheduling
  labels:
    app: app0
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: worker-1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-11
  namespace: scheduling
  labels:
    app: app1
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: worker-1

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-12
  namespace: scheduling
  labels:
    app: app1
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: worker-2